FROM almalinux:8
LABEL course=Devops \
      trainer=Sriram \
      duration=100hrs 

 # we have 100's of images present in the docker machine how can u get the required image is through these

 # labels.

 # docker images --filter label=course=Devops ---> gets the image which has label course=Devops