# COPY instruction is used to copy files or directories from the host machine to the Docker image. 

# This instruction is often used during the Docker image building process to include necessary files or 

# dependencies in the image.

FROM nginx
RUN rm -rf /usr/share/nginx/html/index.html
COPY index.html /usr/share/nginx/html/