FROM almalinux:8
ADD hello.txt /tmp
ADD https://raw.githubusercontent.com/sriram-git-6/docker-files/master/README.md /tmp

# ADD instruction can download the files from internet and copies it into docker image.
# login into container and check the 2 files
