FROM almalinux:8
ADD hello.txt /tmp
ADD https://raw.githubusercontent.com/sriram-git-6/docker-files/master/README.md /tmp
Add sample-1.tar /tmp

# ADD instruction can download the files from internet and copies it into docker image.
# And it automatically extracts the contents of the tar or zip file when it is copied into the docker file.
# login into container and check the 2 files
