FROM almalinux:8
# almalinux is same as centos
RUN yum install epel-release -y
# RUN instruction is used to install packages and run commands and run instruction is run at image creation 
RUN yum install nginx -y
# CMD keeps your container running ..and CMD instruction is run at the time of container creation
