# suppose our microservice needs to connect to mongodb for that catalogue requires 

# mongodb url, portnumber, username and password.

# this information we can provide through ENV instruction.

FROM almalinux:8
ENV NAME=SRIRAM \
    CITY=BANGALORE \
    ADDRESS=MADHAPUR 

# Create image from above docker file.

# docker image build -t env:v1 

# docker run image_id env --> this command creates container and executes env command inside the container

# and displays hostname and env variables defined in the docker file.

# docker run centos ping google.com

# Docker will pull the CentOS image, create a new container based on that image, 

# and then execute the ping google.com command within the container.

# docker run -d image_id sleep 20

# The above container runs for 20sec and exits

